dist: trusty

language: java
jdk:
  - oraclejdk8
  - oraclejdk9
  - openjdk11

addons:
    sonarcloud:
        organization: "robstoll-github"
        token:
            secure: $SONAR_TOKEN

before_install:
 - chmod +x ./gradlew
install: true

script:
  - |
    if [ "$TRAVIS_JDK_VERSION" != openjdk11 ]; then
        ./gradlew buildAllJvm buildAllAndroid detekt
    else
        ./gradlew build detekt
    fi
  - |
    if [ "$TRAVIS_TEST_RESULT" == 0 ] && [ "$TRAVIS_JDK_VERSION" == openjdk11 ]; then
        sonar-scanner \
            -Dsonar.projectVersion=0.14.3 \
            -Dsonar.projectKey=robstoll_kbox \
            -Dsonar.kotlin.detekt.reportPaths=build/reports/detekt/detekt.xml \
            -Dsonar.sources="\
                kbox-android/src/main/kotlin, \
                kbox-common/src/main/kotlin,\
                kbox-js/src/main/kotlin,\
                kbox-jvm/src/main/kotlin" \
            -Dsonar.tests=kbox-common/src/test/kotlin \
            -Dsonar.coverage.jacoco.xmlReportPaths=kbox-jvm/build/reports/jacoco/report.xml
    fi

before_cache:
    - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
    - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/wrapper/
    - $HOME/.gradle/caches/
